import { HashMap } from "./HashMap.mjs";

const test = new HashMap()

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')
test.set('moon', 'silver')

console.log(test.buckets)
console.log(test.length())
console.log(test.capacity)
console.log(test.capacity)
console.log(test.get('apple'))
console.log(test.keys())
console.log(test.values())
console.log(test.entries())
console.log(test.length())
console.log('does it contains key apple? ' + test.has('apple'))
// 
test.clear()
console.log(test)

test.set('apple', 'red')
test.set('banana', 'yellow')
test.remove('banana')
console.log(test.buckets)
console.log(test.length())